name: "CI/CD"
on:
  push:
    branches:
      - main-v2

jobs:
  lambda_update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Gather AWS Permissions
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload zip to lambdas
        run: cd build && for filename in *.js; do

          lambda_function_name=$(basename "$filename" .js)
          zip_filename="${lambda_function_name}.zip"

          zip -r "$zip_filename" "$filename"

          aws lambda update-function-code --function-name
          "$lambda_function_name" --zip-file "fileb://$zip_filename"

          echo "Uploaded $zip_filename to lambda ':' $lambda_function_name"

          done

      - name: Clean up
        run: rm -f *.zip
